### ISSUE TITLE
Error at the end of application

### ISSUE THREAD

**Issue by lewlian** [Corfucinas/crypto-candlesticks#114]
Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 298, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: could not convert string to float: 't'

**Comment by Corfucinas** [comment]
Hi @lewlian 

Could you copy the entire stack trace? Also, what commands did you used to download the data? (So I can reproduce it)

**Comment by Corfucinas** [comment]
@lewlian 

There was a potential issue with Bitfinex API requiring USDT pairs as UST, I have updated this in 0.1.6, upgrade and let me know if the error is still there
